### ISSUE TITLE
Feature Request: Add TCP support

### ISSUE THREAD

**Issue by vitalis** [LeeroyDing/json_logger#1]
Hi, is it possible to add TCP support ?

**Comment by LeeroyDing** [comment]
Currently I do not have time to spend on this, but it's of course possible.

TCP support would require more work because a connection must be maintained.

**Comment by LeeroyDing** [comment]
Will push a new version with basic TCP support that would start a connection each time logging is requested.

**Comment by LeeroyDing** [comment]
TCP is supported now :)

**Comment by vitalis** [comment]
@LeeroyDing Great news!!! Thank you
